INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('14', '1', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`, `Litros`) VALUES ('15', '2', '1', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('16', '3', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('17', '3', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('18', '4', '3');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('19', '4', '2');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('20', '4', '2');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`, `Litros`) VALUES ('21', '4', '1', '0.3');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`, `Litros`) VALUES ('23', '4', '1', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`, `Litros`) VALUES ('27', '4', '1', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`, `Litros`) VALUES ('17', '4', '1', '0.3');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('18', '5', '3');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('19', '5', '2');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('20', '5', '2');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`, `Litros`) VALUES ('21', '5', '1', '0.4');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('23', '5', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('24', '5', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`, `Litros`) VALUES ('17', '5', '1', '0.3');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`, `Litros`) VALUES ('17', '7', '1', '0.3');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('29', '8', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('25', '9', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('18', '10', '3');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('19', '10', '2');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('20', '10', '2');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('21', '10', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`, `Litros`) VALUES ('23', '10', '1', '0.3');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`, `Litros`) VALUES ('24', '10', '1', '0.3');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('17', '10', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('17', '11', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('15', '13', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('17', '13', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`, `Litros`) VALUES ('26', '14', '1', '0.3');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`, `Litros`) VALUES ('16', '15', '1', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('15', '17', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('18', '19', '3');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('19', '19', '2');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('20', '19', '2');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('21', '19', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`, `Litros`) VALUES ('23', '19', '1', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`, `Litros`) VALUES ('28', '19', '1', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`) VALUES ('17', '19', '1');
INSERT INTO `oficinapap`.`intervencao_materiais` (`idMaterial`, `idIntervencao`, `Unidades`, `Litros`) VALUES ('30', '22', '1', '2');
