INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('15VD78', '1', 'Ford', 'Fiesta 2013', '2013-08-25', '27B', 'Azul metalico');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('SD6431', '1', 'Mercedes', 'AMG Classe A', '2016-12-14', '696', 'Preto Escuro');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('5373TK', '2', 'Renault ', 'Megane R.S.', '2021-8-24', 'GNE', 'Preto');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('69RS12', '3', 'Opel', 'Astra G', '2000-6-15', 'Z-205', 'Preto');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('6863TV', '4', 'Pegeot', '3008', '2021-11-26', 'KPL', 'Cinza');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('35EF85', '5', 'Ford', 'Focus', '2019-9-25', '7409', 'Laranja');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('15FD96', '6', 'Mercedes', 'EQE', '2020-08-21', '799', 'Branco Diamante');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('PT5457', '7', 'Opel', 'Astra 5', '2020-11-25', '50B', 'Vermelho');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('5373TK', '8', 'Ford', 'Mustang Mach-E GT', '2020-05-21', 'D4', 'Vermelho');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('5373TK', '9', 'Ford', 'Mustang Mach-E GT', '2020-05-29', 'B3', 'Azul');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('69RS12', '10', 'Opel', 'Astra G', '2000-6-15', 'Z-205', 'Preto');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('64PT08', '11', 'Volkswagen', 'VW T-CROSS', '2021-05-25', '4M', 'Laranja');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('CR54AS', '12', 'Volkswagen', 'GOLF VARIANT', '2017-02-15', '2T', 'Preto');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('DR15WR', '13', 'Ford', 'S-MAX', '2020-01-25', '0FA', 'Branco');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('02TR25', '14', 'Skoda', 'SKODA KAROQ', '2019-12-15', 'LF3P', 'Vermelho');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('51HM15', '15', 'Mercedes', 'VOLVO X40', '2021-06-17', '729', 'Branco Silver');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('97FE14', '16', 'Fiat', '500 C', '2020-01-25', '903', 'Verde');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('5167GE', '17', 'Mercedes', 'GLB 200D', '2021-06-26', '149', 'Branco Polar');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('0561DR', '18', 'Ford', 'FIESTA ', '2022-06-25', '37L', 'Azul');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('1467XR', '19', 'Fiat', 'TIPO ', '2019-05-15', '551', 'Laranja');
INSERT INTO `oficinapap`.`viaturas` (`Matricula`, `idCliente`, `Marca`, `Modelo`, `DataFabricacao`, `CodigoCor`, `Cor`) VALUES ('15DR15', '20', 'Fiat', '500', '2017-12-25', '296', 'Branco');
